"""Resumable training-state backups + pause/resume (Bitcrush ISSUE-0405).

This module is the trainer-agnostic backbone of the Backup / Pause / Resume
feature. The four training entry points (``run_group_training``,
``run_training``, ``run_multihead_training``, ``run_dual_branch_training``) all
lean on the primitives here so the per-trainer diff stays thin:

* :class:`TrainingStateManager` — crash-safe rotating on-disk backups. Every
  ``save`` writes a *new* file via a tmp file + ``os.replace`` and never
  rewrites an existing backup, so a crash mid-write can only ever damage the
  in-progress temp file, never a previously-good backup (the same discipline
  ``smart_cache._save_index`` uses).
* :func:`capture_rng_states` / :func:`restore_rng_states` — snapshot/restore the
  torch + numpy + CUDA **and python** ``random`` generators. The python
  ``random`` module is what the group/bucket samplers shuffle with, so omitting
  it (as the old ``group_trainer._capture_rng_state`` did) makes an otherwise
  "exact" resume diverge.
* :class:`_FixedBatchSampler` — a ``batch_sampler`` that yields a
  pre-materialised list of index batches, so a run can reproduce an exact batch
  order (and a resume can skip already-consumed batches by slicing the list).
* :class:`BackupCoordinator` — bundles the manager, the ``pause_event`` and the
  periodic cadence for one run; ``None`` ``backup_dir`` makes the whole thing
  inert (today's legacy behaviour, no files written, no resume attempted). Its
  :meth:`~BackupCoordinator.backup_on_exception` context manager snapshots the
  training state when the wrapped block raises, then re-raises — a failure to
  back up never masks the original exception.
* :func:`init_backup` / :func:`paused_result` / :func:`collect_epoch_state` /
  :func:`restore_optimizer_state` / :func:`loader_kwargs` — the shared
  scaffolding each trainer wires around its epoch loop.

**Bit-exactness contract.** With ``dataloader_workers=0`` a mid-epoch resume in
``run_group_training`` reproduces the uninterrupted run bit-for-bit: the epoch's
sample layout is regenerated by restoring the epoch-start python-``random`` state
and re-running ``reshuffle()``, the batch order is replayed from the stored
schedule, and the augmentation/mixup RNG is restored from the mid-epoch
snapshot. With ``workers > 0`` the per-sample ``__getitem__`` randomness reseeds
inside each worker, so a resume is only *statistically* identical, not bit-exact.
"""

from __future__ import annotations

import logging
import os
import random
import re
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Callable, Iterator

import numpy as np
import torch

logger = logging.getLogger(__name__)

BACKUP_FORMAT_VERSION = 1

# backup_{global_step:08d}_{seq:04d}.pt — step orders backups coarsely; seq is a
# monotonic disambiguator so two saves at the same optimizer step never collide
# and always sort by save order.
_BACKUP_RE = re.compile(r"^backup_(\d+)_(\d+)\.pt$")


# ---------------------------------------------------------------------------
# RNG capture / restore
# ---------------------------------------------------------------------------


def _as_device(device: torch.device | str) -> torch.device:
    return device if isinstance(device, torch.device) else torch.device(device)


def capture_rng_states(device: torch.device | str) -> dict:
    """Snapshot every RNG a training step draws from.

    Captures torch (CPU), numpy, **python ``random``**, and — only when the
    device is CUDA and CUDA is actually available — all CUDA generators. The
    python ``random`` snapshot is the one the old ``group_trainer`` helper
    missed; the bucket samplers shuffle with it, so an exact resume needs it.
    """
    state: dict = {
        "torch": torch.get_rng_state(),
        "numpy": np.random.get_state(),
        "python": random.getstate(),
    }
    dev = _as_device(device)
    if dev.type == "cuda" and torch.cuda.is_available():
        state["cuda"] = torch.cuda.get_rng_state_all()
    return state


def restore_rng_states(state: dict, device: torch.device | str) -> None:
    """Restore RNG state captured by :func:`capture_rng_states` (best effort)."""
    if not state:
        return
    if "torch" in state:
        torch.set_rng_state(state["torch"])
    if "numpy" in state:
        np.random.set_state(state["numpy"])
    if "python" in state:
        random.setstate(state["python"])
    dev = _as_device(device)
    if dev.type == "cuda" and torch.cuda.is_available() and "cuda" in state:
        try:
            torch.cuda.set_rng_state_all(state["cuda"])
        except (RuntimeError, ValueError):
            logger.warning("Could not restore CUDA RNG state (device count changed?)")


# ---------------------------------------------------------------------------
# Optimizer resume priming (Prodigy_adv transient-accumulator quirk)
# ---------------------------------------------------------------------------


def prime_optimizer_after_resume(optimizer: torch.optim.Optimizer) -> None:
    """Make the first post-resume optimizer step match an uninterrupted one.

    ``Prodigy_adv`` keeps its LR-adaptation accumulators (``d_numerator`` /
    ``d_denom``) as **instance attributes**, not in ``state_dict``.
    ``Prodigy_adv.init_step`` runs at the *tail* of every ``step`` and sets
    ``self.d_numerator = group['d_numerator'] * beta3`` for the following step —
    but only when ``d_denom`` already exists. A freshly-``load_state_dict``-ed
    optimizer has neither attribute, so its next ``step`` would seed
    ``d_numerator`` WITHOUT the ``beta3`` decay: a ~1e-4 relative drift that
    compounds. Creating a zero ``d_denom`` on the right device and invoking
    ``init_step`` reproduces that tail exactly, leaving the next step
    bit-identical to an uninterrupted one. No-op for optimizers without the
    Prodigy accumulator scheme.
    """
    if not any("d_numerator" in g for g in optimizer.param_groups):
        return
    if hasattr(optimizer, "d_denom"):
        return
    init_step = getattr(optimizer, "init_step", None)
    if init_step is None:
        return
    param = next((p for g in optimizer.param_groups for p in g["params"]), None)
    device = param.device if param is not None else torch.device("cpu")
    optimizer.d_denom = torch.tensor(0.0, device=device)
    init_step()


def capture_optimizer_aux_state(optimizer: torch.optim.Optimizer) -> dict:
    """Snapshot optimizer state that ``state_dict()`` does NOT cover.

    ``Prodigy_adv``'s Kourkoutas-β helper keeps a per-layer ``sum_sq_accumulator``
    (the squared grad-norm of the step just taken) as live tensors on the helper,
    *outside* ``optimizer.state``. The following step's ``prepare_step`` consumes
    it to update the dynamic-β2 EMA. A freshly loaded optimizer starts that
    accumulator at zero, so the first resumed step computes a slightly different
    β2 → a ~1e-4 drift that compounds. Capturing it here (keyed by the helper's
    stable shape-based ``layer_key``) lets :func:`restore_optimizer_aux_state`
    reinstate it and keep resume bit-exact. Returns ``{}`` for optimizers without
    the helper (nothing extra to carry).
    """
    helper = getattr(optimizer, "kourkoutas_helper", None)
    if helper is None:
        return {}
    acc: dict = {}
    for layer_key, st in getattr(helper, "layer_state", {}).items():
        a = st.get("sum_sq_accumulator")
        if isinstance(a, torch.Tensor):
            acc[layer_key] = a.detach().cpu().clone()
    return {
        "kourkoutas_sum_sq": acc,
        "current_step_prepared": int(getattr(helper, "_current_step_prepared", -1)),
    }


def restore_optimizer_aux_state(
    optimizer: torch.optim.Optimizer, aux: dict | None, device: torch.device | str
) -> None:
    """Reinstate the Kourkoutas accumulators captured by
    :func:`capture_optimizer_aux_state` (best effort, no-op without the helper)."""
    helper = getattr(optimizer, "kourkoutas_helper", None)
    if helper is None or not aux:
        return
    saved = aux.get("kourkoutas_sum_sq", {})
    try:
        helper._build_layer_info_if_needed()
        for layer_key, info in helper.layer_info.items():
            params = info["params"]
            dev = params[0].device
            # Force the layer_state entry (and its EMA link to optimizer.state) to
            # exist before we overwrite the accumulator.
            helper._get_or_init_layer_ema_tensor(layer_key, params, dev)
            if layer_key in saved:
                helper.layer_state[layer_key]["sum_sq_accumulator"] = saved[layer_key].to(dev)
        helper._current_step_prepared = int(aux.get("current_step_prepared", -1))
    except Exception:  # pragma: no cover - defensive: never let a resume crash here
        logger.warning("Could not restore Kourkoutas accumulators; resume may drift slightly", exc_info=True)


# ---------------------------------------------------------------------------
# Numpy sanitisation
# ---------------------------------------------------------------------------


def sanitize_for_backup(obj):
    """Recursively convert numpy scalars/arrays to plain python.

    ``best_metrics`` carries numpy scalars out of ``compute_*_metrics``; those
    survive ``torch.save`` but bloat the backup and break the JSON round-trip
    the Engine does with the result dict. Mirrors the strip at
    ``group_trainer._compare_promote_finalize`` — we sanitise the *values* here
    rather than only popping the internal arrays.
    """
    if isinstance(obj, dict):
        return {k: sanitize_for_backup(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return type(obj)(sanitize_for_backup(v) for v in obj)
    if isinstance(obj, np.generic):
        return obj.item()
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    return obj


# ---------------------------------------------------------------------------
# Fixed batch sampler (schedule replay)
# ---------------------------------------------------------------------------


class _FixedBatchSampler:
    """A ``batch_sampler`` that yields a pre-materialised list of index batches.

    Driving a ``DataLoader`` with this makes the batch order deterministic and
    inspectable: ``list(train_sampler)`` is materialised once per epoch, stored
    in the backup, and on resume the loader runs over ``schedule[batch_in_epoch:]``
    so no already-consumed image is loaded twice.
    """

    def __init__(self, batches: list[list[int]]) -> None:
        self._batches = [list(b) for b in batches]

    def __iter__(self) -> Iterator[list[int]]:
        yield from self._batches

    def __len__(self) -> int:
        return len(self._batches)


# ---------------------------------------------------------------------------
# Fingerprint (resume-compatibility gate)
# ---------------------------------------------------------------------------


def make_fingerprint(
    *,
    class_names: list[str],
    num_classes: int,
    max_epochs: int,
    multi_label: bool,
    ordinal: bool,
    best_model_name: str,
    model_size: str,
) -> dict:
    """Identity of the run a backup belongs to.

    A resume only proceeds when the on-disk backup's fingerprint matches the
    current config; a mismatch (e.g. the class list changed) means the stored
    optimizer/model state no longer fits, so the run starts fresh instead of
    crashing on a shape mismatch. ``model_size`` folds in both the group
    trainer's ``backbone_variant`` and the binary trainer's ``model_size``.
    """
    return {
        "class_names": list(class_names),
        "num_classes": int(num_classes),
        "max_epochs": int(max_epochs),
        "multi_label": bool(multi_label),
        "ordinal": bool(ordinal),
        "best_model_name": str(best_model_name),
        "model_size": str(model_size),
    }


def fingerprint_matches(saved: dict | None, current: dict) -> bool:
    """True iff every key of ``current`` matches ``saved`` (order-sensitive lists)."""
    if not saved:
        return False
    for key, value in current.items():
        if saved.get(key) != value:
            return False
    return True


# ---------------------------------------------------------------------------
# TrainingStateManager
# ---------------------------------------------------------------------------


class TrainingStateManager:
    """Crash-safe rotating backups of a training-state dict.

    Each :meth:`save` writes to a temp file and ``os.replace``\\ s it into a
    *new* ``backup_{step:08d}_{seq:04d}.pt`` filename, then prunes the oldest
    files beyond ``keep``. Because an existing backup is never rewritten in
    place, a crash mid-write can only damage the temp file; the previous good
    backup is untouched. :meth:`load_latest` walks newest→oldest and skips any
    file that fails to unpickle.
    """

    def __init__(self, backup_dir: str | Path, *, keep: int = 2) -> None:
        self.backup_dir = Path(backup_dir)
        self.keep = max(1, int(keep))
        # Global monotonic disambiguator. Seeded past any existing backup so a
        # resume that saves at a step already on disk still sorts *after* it.
        self._seq = self._max_existing_seq() + 1

    # -- filename helpers ---------------------------------------------------

    def _max_existing_seq(self) -> int:
        best = -1
        if not self.backup_dir.is_dir():
            return best
        for path in self.backup_dir.glob("backup_*.pt"):
            m = _BACKUP_RE.match(path.name)
            if m:
                best = max(best, int(m.group(2)))
        return best

    @staticmethod
    def _sort_key(path: Path) -> tuple[int, int]:
        m = _BACKUP_RE.match(path.name)
        # matched files only ever reach here
        return (int(m.group(1)), int(m.group(2)))  # type: ignore[union-attr]

    def list_backups(self) -> list[Path]:
        """Valid backup files, oldest→newest by (global_step, seq). Ignores
        stray ``.tmp`` files and anything not matching the backup pattern."""
        if not self.backup_dir.is_dir():
            return []
        files = [p for p in self.backup_dir.glob("backup_*.pt") if _BACKUP_RE.match(p.name)]
        return sorted(files, key=self._sort_key)

    # -- save ---------------------------------------------------------------

    def save(self, state: dict, *, reason: str) -> Path:
        """Write ``state`` as a new rotating backup; return its path.

        Stamps ``version`` / ``reason`` / ``saved_at`` onto a shallow copy of
        ``state`` (the caller's dict is not mutated).
        """
        self.backup_dir.mkdir(parents=True, exist_ok=True)
        payload = dict(state)
        payload["version"] = BACKUP_FORMAT_VERSION
        payload["reason"] = reason
        payload["saved_at"] = time.time()

        global_step = int(payload.get("global_step", 0) or 0)
        seq = self._seq
        self._seq += 1
        final = self.backup_dir / f"backup_{global_step:08d}_{seq:04d}.pt"
        tmp = self.backup_dir / f"{final.name}.tmp"
        torch.save(payload, tmp)
        os.replace(tmp, final)
        logger.info("Saved training backup %s (reason=%s)", final.name, reason)
        self._prune()
        return final

    def _prune(self) -> None:
        backups = self.list_backups()
        for stale in backups[: max(0, len(backups) - self.keep)]:
            try:
                stale.unlink()
            except OSError:
                logger.warning("Could not prune old backup %s", stale, exc_info=True)

    # -- load ---------------------------------------------------------------

    def load_latest(self) -> dict | None:
        """Newest un-corrupted backup as a dict, or ``None`` if none load.

        ``weights_only=False`` is REQUIRED: the payload holds python/numpy RNG
        tuples and optimizer state, not just tensors. These are trusted local
        files. torch>=2.6 flipped the default to ``True`` so it is passed
        explicitly. A corrupt newest file is skipped in favour of the next
        older one.
        """
        for path in reversed(self.list_backups()):
            try:
                return torch.load(path, map_location="cpu", weights_only=False)
            except Exception:
                logger.warning("Backup %s failed to load; trying next-older", path.name, exc_info=True)
        return None

    def delete_all(self) -> None:
        """Remove all backup files (incl. stray tmps) and the backup dir (best effort)."""
        if not self.backup_dir.exists():
            return
        for path in self.backup_dir.glob("backup_*.pt*"):  # matches .pt and .pt.tmp
            try:
                path.unlink()
            except OSError:
                pass
        try:
            self.backup_dir.rmdir()
        except OSError:
            pass


# ---------------------------------------------------------------------------
# BackupCoordinator — per-run backup/pause orchestration shared by all trainers
# ---------------------------------------------------------------------------


def _looks_like_oom(exc: BaseException) -> bool:
    if isinstance(exc, getattr(torch.cuda, "OutOfMemoryError", ())):
        return True
    text = str(exc).lower()
    return "out of memory" in text or "cuda oom" in text


class BackupCoordinator:
    """Per-run bundle of the state manager, the pause event and the cadence.

    ``backup_dir=None`` makes it inert: no manager, no files, ``paused`` still
    honoured but with no backup to hand back (legacy behaviour). Shared by all
    four trainers so periodic/pause/exception handling lives in one place.
    """

    def __init__(
        self,
        *,
        backup_dir: str | Path | None,
        keep: int = 2,
        pause_event: object | None = None,
        backup_every_steps: int = 500,
        cb: Callable[[dict], None] | None = None,
    ) -> None:
        self.manager = TrainingStateManager(backup_dir, keep=keep) if backup_dir else None
        self.pause_event = pause_event
        self.backup_every_steps = int(backup_every_steps)
        self.cb = cb
        self.last_backup_path: str | None = None

    @property
    def enabled(self) -> bool:
        return self.manager is not None

    @property
    def paused(self) -> bool:
        return self.pause_event is not None and bool(self.pause_event.is_set())

    def save(self, state: dict, *, reason: str, emit: bool = True) -> Path | None:
        if self.manager is None:
            return None
        path = self.manager.save(state, reason=reason)
        self.last_backup_path = str(path)
        if emit and self.cb is not None:
            self.cb({
                "type": "backup_complete",
                "backup_path": str(path),
                "global_step": state.get("global_step"),
                "epoch": state.get("epoch"),
                "reason": reason,
            })
        return path

    def delete_backups(self) -> None:
        """Drop all backups (successful completion — they are obsolete)."""
        if self.manager is not None:
            self.manager.delete_all()

    @contextmanager
    def backup_on_exception(self, collect_state: Callable[[], dict]):
        """Snapshot training state if the wrapped block raises, then re-raise.

        On any ``Exception``: best-effort ``torch.cuda.empty_cache()`` when the
        error looks OOM-ish (frees VRAM so the backup's checkpoint IO can run),
        then ``save(collect_state(), reason="exception")`` — which emits the
        ``backup_complete`` callback — inside its own ``try/except``: a backup
        failure must NEVER mask the original exception, which always propagates.
        """
        try:
            yield
        except Exception as exc:
            if _looks_like_oom(exc):
                try:
                    if torch.cuda.is_available():
                        torch.cuda.empty_cache()
                except Exception:
                    logger.warning("empty_cache() during exception backup failed", exc_info=True)
            if self.enabled:
                try:
                    self.save(collect_state(), reason="exception")
                except Exception:
                    logger.warning(
                        "Failed to back up training state on exception", exc_info=True
                    )
            raise

    def on_boundary(self, collect_state: Callable[[], dict], global_step: int) -> str | None:
        """Called at every gradient-accumulation boundary.

        Returns ``"stop"`` when the epoch loop should break (pause requested),
        else ``None``. A pause always saves (``reason="pause"``); otherwise a
        periodic backup fires when ``global_step`` hits the cadence.
        """
        if self.paused:
            self.save(collect_state(), reason="pause")
            return "stop"
        if (
            self.manager is not None
            and self.backup_every_steps
            and global_step % self.backup_every_steps == 0
        ):
            self.save(collect_state(), reason="periodic")
        return None

    def load_resume(self, fingerprint: dict, *, resume_from: str | Path | None) -> dict | None:
        """Load the newest compatible backup for a resume, or ``None``.

        ``resume_from`` may point at a specific backup dir/file or be falsy (use
        this coordinator's manager). Emits a ``resume_skipped`` warning callback
        and returns ``None`` on fingerprint mismatch or an unloadable file, so
        the caller starts fresh rather than crashing.
        """
        manager = self.manager
        if resume_from:
            rp = Path(resume_from)
            if rp.is_file():
                try:
                    state = torch.load(rp, map_location="cpu", weights_only=False)
                except Exception:
                    logger.warning("resume_from file %s failed to load", rp, exc_info=True)
                    self._emit_resume_skipped("unloadable_backup")
                    return None
                return self._check_fingerprint(state, fingerprint)
            manager = TrainingStateManager(rp, keep=self.manager.keep if self.manager else 2)
        if manager is None:
            return None
        state = manager.load_latest()
        if state is None:
            return None
        return self._check_fingerprint(state, fingerprint)

    def _check_fingerprint(self, state: dict, fingerprint: dict) -> dict | None:
        if not fingerprint_matches(state.get("fingerprint"), fingerprint):
            logger.warning(
                "Resume fingerprint mismatch (saved=%s current=%s) — starting fresh",
                state.get("fingerprint"), fingerprint,
            )
            self._emit_resume_skipped("fingerprint_mismatch")
            return None
        return state

    def _emit_resume_skipped(self, reason: str) -> None:
        if self.cb is not None:
            self.cb({
                "type": "resume_skipped",
                "reason": reason,
                "status_text": "Backup incompatible with current run — starting fresh",
            })


# ---------------------------------------------------------------------------
# Shared per-trainer scaffolding (all four run_* entry points use these)
# ---------------------------------------------------------------------------


def init_backup(
    config, pause_event: object | None, cb: Callable[[dict], None], **fingerprint_kwargs
) -> tuple[BackupCoordinator, dict, dict | None]:
    """Build the run's coordinator + fingerprint and load its resume state.

    ``config`` only needs ``backup_dir`` / ``backup_every_steps`` /
    ``resume_from`` (all four trainer configs carry them). A resume is only
    attempted when ``resume_from`` is explicitly set — a bare ``backup_dir``
    never auto-resumes.
    """
    coordinator = BackupCoordinator(
        backup_dir=config.backup_dir, pause_event=pause_event,
        backup_every_steps=config.backup_every_steps, cb=cb,
    )
    fingerprint = make_fingerprint(**fingerprint_kwargs)
    resume_state = (
        coordinator.load_resume(fingerprint, resume_from=config.resume_from)
        if config.resume_from else None
    )
    return coordinator, fingerprint, resume_state


def paused_result(
    cb: Callable[[dict], None], epoch: int, global_step: int, backup_path, **extra
) -> dict:
    """Emit ``training_paused`` and build the trainer's paused return value."""
    bp = str(backup_path) if backup_path else None
    cb({
        "type": "training_paused", **extra,
        "epoch": epoch, "global_step": global_step, "backup_path": bp,
    })
    return {"paused": True, "backup_path": bp, "epoch": epoch, "global_step": global_step}


def collect_epoch_state(
    *,
    fingerprint: dict,
    trainer: str,
    epoch: int,
    global_step: int,
    eff_bs: int,
    scheduler_t_max: int,
    model,
    optimizer,
    scheduler,
    best: dict,
    batch_in_epoch: int = 0,
    **extra,
) -> dict:
    """The shared core of every trainer's backup envelope.

    Default shape is epoch-restart (``batch_in_epoch=0``); trainer-specific
    fields (ema/swa/dcw/rng/schedule/...) ride in via ``extra``. ``best`` is
    copied and its ``best_metrics`` numpy-sanitised here so callers pass the
    live dict straight through.
    """
    best = dict(best)
    best["best_metrics"] = sanitize_for_backup(best.get("best_metrics") or {})
    return {
        "fingerprint": fingerprint,
        "trainer": trainer,
        "epoch": epoch,
        "batch_in_epoch": batch_in_epoch,
        "global_step": global_step,
        "eff_bs": eff_bs,
        "scheduler_t_max": scheduler_t_max,
        "model": {k: v.detach().cpu() for k, v in model.state_dict().items()},
        "optimizer": optimizer.state_dict(),
        "optimizer_aux": capture_optimizer_aux_state(optimizer),
        "scheduler": scheduler.state_dict(),
        "best": best,
        **extra,
    }


def restore_optimizer_state(resume_state: dict, optimizer, scheduler, device) -> None:
    """Restore optimizer + scheduler from a backup, including the Prodigy
    priming and Kourkoutas aux accumulators that keep the resume bit-exact."""
    optimizer.load_state_dict(resume_state["optimizer"])
    prime_optimizer_after_resume(optimizer)
    restore_optimizer_aux_state(optimizer, resume_state.get("optimizer_aux"), device)
    scheduler.load_state_dict(resume_state["scheduler"])


def loader_kwargs(num_workers: int, *, pin_memory: bool = True, prefetch_factor: int = 4) -> dict:
    """DataLoader kwargs honouring ``config.dataloader_workers`` (0 disables the
    worker-only persistent/prefetch options; the trainers previously hardcoded 4/6)."""
    n = max(0, int(num_workers))
    kwargs: dict = {"num_workers": n, "pin_memory": pin_memory}
    if n > 0:
        kwargs.update(persistent_workers=True, prefetch_factor=prefetch_factor)
    return kwargs
